sudo: false

language: java
include:
- language: java
  jdk: oraclejdk8
  script: mvn clean install -DskipTests=false
  # Use JDK 8u45. The above line just causes the use of a minor version of Java 8.
  addons:
  apt:
  packages:
  - oracle-java8-installer
